#!/bin/sh
set -e
. /usr/share/debconf/confmodule

APP_DIR=/usr/share/kat-mula

python3 -m venv ${APP_DIR}/venv

echo "Setting up mula environment."
${APP_DIR}/venv/bin/pip install --upgrade pip > /dev/null
${APP_DIR}/venv/bin/pip install --requirement ${APP_DIR}/app/requirements.txt > /dev/null

if [ ! -d /etc/kat ]; then
    mkdir /etc/kat
fi

if [ ! -f /etc/kat/mula.conf ]; then
    cp /usr/share/kat-mula/app/.env-dist /etc/kat/mula.conf
    cp /usr/share/kat-mula/app/logging.prod.json /etc/kat/logging.mula.json

    sed -i 's/SCHEDULER_LOG_CFG=.*$/SCHEDULER_LOG_FILE=\/etc\/kat\/logging.mula.json/' /etc/kat/mula.conf
    sed -i 's/SCHEDULER_API_PORT=.*$/SCHEDULER_API_PORT=8004/' /etc/kat/mula.conf
fi

ln -s /etc/kat/mula.conf /usr/share/kat-mula/app/.env

chmod 640 /etc/kat/mula.conf
chmod 640 /etc/kat/logging.mula.json
chmod 750 /usr/lib/systemd/system/kat-mula.service

db_stop || true
