name: Check code quality
on: [push]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        id: py38
        with:
          python-version: 3.8
          cache: pip

      - name: Install pre-commit
        run: pip install pre-commit==2.20.0

      - uses: actions/cache@v3
        with:
          path: ~/.cache/pre-commit
          key: pre-commit|${{ steps.py38.outputs.python-version }}|${{ hashFiles('.pre-commit-config.yaml') }}

      - name: Run pre-commit
        run: pre-commit run --all-files --show-diff-on-failure --color always
